### ISSUE TITLE
problem compiling examples in arduino compiler 1.6.6

### ISSUE THREAD

**Issue by kcobley** [AndreiDegtiarev/AWind#1]
Opening Guages.pde and 'verify/compile' - compiler has several errors like this:

Arduino: 1.6.6 (Windows XP), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from C:\Program Files\Arduino\libraries\AWind/GaugeBar.h:22:0,

```
             from sketch\GaugesWindow.h:20,

             from C:\Documents and Settings\Owner\Desktop\Arduino\awind_full\AWind\examples\Gauges\Gauges.pde:28:
```

C:\Program Files\Arduino\libraries\AWind/Gauge.h:34:46: error: 'constexpr' needed for in-class initialization of static data member 'const float Gauge::_sector_angle_rad' of non-integral type [-fpermissive]

  static const float _sector_angle_rad=3.14/2*0.8;

```
                                          ^
```

In file included from sketch\GaugesWindow.h:21:0,

```
             from C:\Documents and Settings\Owner\Desktop\Arduino\awind_full\AWind\examples\Gauges\Gauges.pde:28:
```

C:\Program Files\Arduino\libraries\AWind/GaugeRadialPointer.h:30:46: error: 'constexpr' needed for in-class initialization of static data member 'const float GaugeRadialPointer::_sector_angle_rad' of non-integral type [-fpermissive]

  static const float _sector_angle_rad=3.14/2*0.8;

```
                                          ^
```

In file included from C:\Program Files\Arduino\libraries\AWind/ChartWindow.h:26:0,

```
             from sketch\GaugesWindow.h:22,

             from C:\Documents and Settings\Owner\Desktop\Arduino\awind_full\AWind\examples\Gauges\Gauges.pde:28:
```

C:\Program Files\Arduino\libraries\AWind/ChartDC.h:35:29: error: 'constexpr' needed for in-class initialization of static data member 'const float ChartDC::AutoMin' of non-integral type [-fpermissive]

  static const float AutoMin=1e-8;

```
                         ^
```

C:\Program Files\Arduino\libraries\AWind/ChartDC.h:36:29: error: 'constexpr' needed for in-class initialization of static data member 'const float ChartDC::AutoMax' of non-integral type [-fpermissive]

  static const float AutoMax=1e8;

```
                         ^
```

exit status 1
Error compiling.

**Comment by AndreiDegtiarev** [comment]
Compile errors are resolved for arduino 1.6.6
