### ISSUE TITLE
AFrame and Asensor missing from zip

### ISSUE THREAD

**Issue by kcobley** [AndreiDegtiarev/AWind#2]
Previous release included folders AFrame and ASensor. AWind refers to Log.h which was in AFrame and is not present in AWind-master in the new release. Sorry - if I knew how, I would fix this myself (assuming this is possible). Thanks for a very useful library!

**Comment by AndreiDegtiarev** [comment]
Did you download awind_full.zip? Only this zip-file contains all libraries.

**Comment by kcobley** [comment]
Hi Andrei,

No. I downloaded AWind-master.zip right from the GitHub page. Pretty sure I did that last time because I went back to the previous release to check if it was in there, and the zip had all three libraries.

K.

**Comment by AndreiDegtiarev** [comment]
Hi Kcobley

hopefully everething is working now?

Andrei

**Comment by kcobley** [comment]
There seems to be a bug in Gauges - it works perfectly straight from upload, but if I power down the board then the buttons don't work at all after power up -display is fine, but no interaction.

Am I right to expect that the code should be non volatile? I'm new to arduino and also to classes - I'm a hardware engineer by trade, and I'm used to PICs with simple c compiler. It's all a but new to me.... Slightly shocked by how poor the IDE is - no debugger etc.

Otherwise it seems to work OK now that I have all the librarys. 

Once again, thankyou for the library-a huge leg-up as we say in the UK. Saved lots of time for my application. If I can help in any way, let me know. 

Kevin

**Comment by AndreiDegtiarev** [comment]
Hi Kelvin,
I have tested Gauges example and I’m not able reproduce the behavior you described (for tests I have DUE). In general, after power is switched off/on everything have to be reset into initial stage. Do you observe wrong behavior with touch, if you disconnect power cable and wait a little bit?  
I agree Arduino IDE isn’t the best tool for Arduino development. Personally I use VS2015 community edition + VisualMicro plug-in – everything is free for personal use.
Thank you for your kind words. It is always motivating to hear something like that. 
Of course any help is appreciated. For the start it is interesting to know more about your project, you are going/ you have already implemented with the help of AWind library. Based on this information we can extend AWind with features that especially interesting for your project, or we can extend examples with your project - we will see. 

Andrei

**Comment by kcobley** [comment]
Hi,

Ok. My hardware is different- Sainsmart MEGA2560 with led shield and QVT320 lcd.

It seems most likely that it's to do with the programming process that leaves a pin set in a way that helps. Or at least that's a possibility.. I powered up the board on its own after 24hrs and there was no action on the gui controls - code was running and graph was updated but buttons don't respond. 

Plugged it in , upload, works immediately.. Unplug an wait a few secs-broken again when restarted... Completely consistent. 

I'll have a look at the data sheet and see if I can think of anything...

My application is a Geiger counter instrument. I made one using a pic and led numerical display , but I never finished it - it looked ugly and wasn't nice to use, and battery life was poor. I'm reusing the power supply and probe circuits and using the arduino and lcd for the counter and the gui. The gauges example is almost exactly what I need - just a few different buttons etc. I'm doing this for fun - for the kids and myself - they can see how many radioactive things we have in our house (photo lenses,glass bowls, lamp mantles etc. )

Cheers for now,

Kevin.

**Comment by AndreiDegtiarev** [comment]
Hi Kevin,
I am happy to hear that the example Gauges that I made just to demonstrate AWind functionality is used for “real stuff”. If you have any difficulties to adjust it to your needs just let me know. Be careful with radioactivity :-)
About the problem with restart – I can imagine, that because of Mega has less SRAM as DUE, the memory may become corrupt. To test that, try to remove some controls and check results. 

Regards,
Andrei
