### ISSUE TITLE
Touch not working

### ISSUE THREAD

**Issue by SuperYeti** [AndreiDegtiarev/AWind#3]
I'm playing around with the examples and my first extension of one of them, and touch isn't working, and no button presses are reacting to anything. I've tried with the UTouch examples, and it's working fine, so it seems like it's something with the AWind library. I also tried checking if the touches are available in the main app loop, and they are, it just seems like it's not bubbling up through the lib.  Update: I un-commented some debug statements in the WindowsManager.h, and I can see the touches make it that far. I just had it work until I connected the serial monitor, than it stopped. It seems related to that, any suggestions?

**Comment by AndreiDegtiarev** [comment]
This effect is new for me. What kind of hardware and which version of arduino do you use?

**Comment by SuperYeti** [comment]
Sainsmart Arduino mega 2650
Sainsmart TFT shield
Sainsmart TFT touch 3.2" display

Arduino 1.7

**Comment by AndreiDegtiarev** [comment]
I have also everything the same like yours except the board. I am using DUE. Could you please try the simplest example "Text" and before test it completly disconnect your board from power and connect it again.
