### ISSUE TITLE
Automatic exit after x time from a dialog page 

### ISSUE THREAD

**Issue by elpapais** [AndreiDegtiarev/AWind#8]
Hi Andrei!
I'm using 8 dialogs and a main window and a project folder .ino.
i have some sensors in loop() routine.
The sensors, in main window work fine, but if i'm in a dialog window i cant see the sensors...
like removed  from loop() function.
Is there an solution to see everiwere the sensors? or how i can automatic close the dialog window and come back in the main window?

regards.

**Comment by elpapais** [comment]
solved.

**Comment by AndreiDegtiarev** [comment]
Cool :-)
